### PR TITLE
Add role ROLE_USER to user returned from UserProvider

### PR DESCRIPTION
**Pull request by pakulin**
Make returned user consistent with Symfony conventions

### CODE REVIEW

**Comment by joostfaassen** [comment]
@pakulin there already exists a UserProvider in the `userbase/client` package that this library depends on.

I think the only difference is the automatic adding of the `ROLE_USER`, right?

I'm not a big fan of the code duplication.

@boite what do you think, how would you handle this?

@pakulin would it solve your problem if you simply checked for `IS_AUTHENTICATED_FULLY` instead of `ROLE_USER`?

**Comment by pakulin** [comment]
@joostfaassen As it is a Symfony bundle, I think it should contain UserProvider and client should not. 
Also client shouldn't know about User class at all (_itemToUser_ function), that's too much coupling as for me. User class should be created in bundle

**Comment by joostfaassen** [comment]
The UserProvider is also used in silex and radvance based projects, which are not using the symfony bundle, but uses the symfony components.

**Comment by boite** [comment]
@pakulin @joostfaassen The recommended way to grant ROLE_USER by default is probably [as described in the Symfony docs](https://symfony.com/doc/current/security.html#roles); something like this in `UserBase\Client\Model\User.getRoles()`:-

```php

public function getRoles(): array
{
    $roles = $this->roles;
    // guarantee every user at least has ROLE_USER
    $roles[] = 'ROLE_USER';

    return array_unique($roles);
}
```

We cannot say for certain, without reviewing every app that makes use of this User class, whether or not this will have any unintended consequence.

What exactly do we gain by granting `ROLE_USER` by default?

**Pull request closed without merging**
